language : android
android:
  components:
   - platform-tools
   - tools
   - build-tools-21.1.2
   - sys-img-armeabi-v7a-android-21

# Start emulator
script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
